version: '3.9'
services:
  mysql_shard_1:
    image: mysql:8.0
    container_name: mysql_shard_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shard1_db
    ports:
      - "3307:3306"
    volumes:
      - shard1_data:/var/lib/mysql
      - ./create_db_table_1.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_shard_2:
    image: mysql:8.0
    container_name: mysql_shard_2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shard2_db
    ports:
      - "3308:3306"
    volumes:
      - shard2_data:/var/lib/mysql
      - ./create_db_table_2.sql:/docker-entrypoint-initdb.d/init.sql

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    restart: always
    ports:
      - "6033:6033"
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf

  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  node_client:
    build:
      context: ./node_client
    container_name: node_client
    command: ["node", "app.js"]
    depends_on:
      - mysql_shard_1
      - mysql_shard_2
      - proxysql
      - elasticsearch
    environment:
      - MYSQL_HOST=proxysql
      - MYSQL_PORT=6033
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./node_client:/usr/src/app

volumes:
  shard1_data:
  shard2_data:
  es_data:

